### PR TITLE
Patch level 2: Dated 28.01.2020 20:10 IST

### PR DESCRIPTION
**Pull request by OccupationalTern**
Updated fingerprint.goodix.so and fingerprint.goodix.txt files.
Patched: 
GxFpDevice::notify
GxFpDevice::notifyData
goodix_sensor_init

### CODE REVIEW

**Comment by OccupationalTern** [comment]
Updated README.md file as well.

**Review by OccupationalTern — COMMENTED** [review]
Looks good to me.

**Comment by OccupationalTern** [comment]
One thing that I want to clarify is that the amount of change being shown in fingerprint.goodix.txt is ONLY due to the variance in decoded text corresponding to HeX values which I believe are caused due to use of different operating systems and/or HeX Editors. The HeX values are absolutely fine in both fingerprint.goodix.so and fingerprint.goodix.txt files. You can verify them as well.

**Comment by Roker2** [comment]
Sorry, but it is not full list for patches...

**Comment by OccupationalTern** [comment]
Roker2, can you please elaborate more on this? Is there some issue from my end(related to the HeX values I changed)?

**Comment by OccupationalTern** [comment]
Or you want to say that the list of functions to be patched in test-2 branch is still incomplete? If this is so then why you are being sorry? Even I know it is still incomplete(it's mentioned in README.md file's latest commit description in test-2 branch as well).

**Comment by OccupationalTern** [comment]
Greetings!
I haven't heard back from you for a while. Is this branch still alive?

**Review by OccupationalTern — COMMENTED** [review]
Cross checked as well.

**Comment by Roker2** [comment]
Sorry, I found another way.

**Comment by Roker2** [comment]
Write me please in Telegram

**Comment by OccupationalTern** [comment]
As goodix sensor has been fixed and the patches has been merged in the device trees, I will be closing this PR as soon as I get on my PC(GitGub Android app don't provide PR closing option as of now).

**Comment by OccupationalTern** [comment]
*GitHub

**Comment by OccupationalTern** [comment]
Closed.

**Pull request closed without merging**
